### ISSUE TITLE
Eomund doesn't seem to be in the database

### ISSUE THREAD

**Issue by milogert** [ddddirk/lotrdb#7]
See title. Not sure he's in there.

Notice my search includes "Eowyn" (with the same "E" plus accent) yet does not include "Eomund."

<img width="438" alt="eomund" src="https://cloud.githubusercontent.com/assets/5378535/11770093/00d24066-a1bc-11e5-8bf0-e8f462b79067.png">

Cardgame DB is garbage and I would love to use this as a replacement.

**Comment by ddddirk** [comment]
He is included when I search for the same.

![capture](https://cloud.githubusercontent.com/assets/10437289/11776244/c64d5d60-a245-11e5-8e9a-9dcf87e1f820.PNG)

Have you made sure to select *Conflict at the Carrock* in the **Packs** tab?

**Comment by milogert** [comment]
What an embarrassment. Well obviously it's working.. That was the issue.

Thanks for the help and this project looks sweet!

**Comment by ddddirk** [comment]
No problem!
