### ISSUE TITLE
Feature request: Add "notes" section to decks

### ISSUE THREAD

**Issue by rmunn** [ddddirk/lotrdb#9]
Back when the CardgameDB.com deckbuilder was the only one around, I created many decks with it. It provided a section called "Strategy" in the "Save" tab, which I made extensive use of to write myself notes on how I designed the deck to work. E.g., "Try to put Support of the Eagles on Legolas, then get Eagles of the Misty Mountain out and use Vassal of the Windlord to boost it (after attacking, it goes under Eagles of the Misty Mountain). Do that a few times and now Legolas can kill just about anything with 8 Attack."

Now that I've discovered your deckbuilder, I've been transferring my decks to it rather than continue to use CardgameDB's not-quite-as-nice interface. I couldn't transfer them directly, but OCTGN's Deck Converter program has been doing a fine job of turning CardgameDB's deck format into .o8d files, which I could then upload to The Rivendell Councilroom. All is well.

Except for my notes, that is. Since The Rivendell Councilroom doesn't have any way to store notes, when I import .o8d files, my notes get lost. (The .o8d format also allows for a sideboard, which The Rivendell Councilroom doesn't, but I've gotten around that by creating two decks, one called "Eagles deck" and one called "Eagles sideboard".) What I'd like to see is for decks to allow storage for arbitrary text in a "Notes" field. That would allow me to import my decks from CardgameDB or OCTGN without losing information.

Would that be a lot of work? Or would that be relatively simple?

**Comment by ddddirk** [comment]
The biggest problem would be adding it to the decks in such a way that decks with and without a notes field could still be loaded.

I'll try to look into it when I have some more time.

**Comment by rmunn** [comment]
Now that I've looked at your code a little, I might have a suggestion for how to implement this idea. You store decks in local browser storage as a Javascript object with keys `deck`, `deckname`, and `dateUTC`, right? Add another key called `decknotes` (or just `notes` if you prefer, but I think `decknotes` might be better). In your `loadDeck()` function, add something like:

    if ($localstorage.decks[deckname].decknotes === undefined) {
        deck.decknotes = "";
    } else {
        deck.decknotes = $localstorage.decks[deckname].decknotes;
    }

Then in your `saveDeck()` function, add a second parameter called `decknotes`, and simply do:

    $localStorage.decks[deckname].decknotes = decknotes;

while you're storing all the other variables. The value of `decknotes` would come from the value of the `textarea` element that you'd create somewhere in `deck.html`.

Finally, in your `downloadDeck()` and `octgn()` functions, you'd need to add somewhere for the deck notes to be stored -- and you'd need to handle them in `uploadOctgn()`. And that's it, you're done.

**Comment by ddddirk** [comment]
I was planning to do something very much like this, yes.
I'm not an OCTGN user myself, could you provide a pastebin of an o8d file with a notes section?

**Comment by rmunn** [comment]
Sure; https://gist.github.com/rmunn/3dde464389be1fd4eef1 shows what a notes file looks like with notes in it.

By the way, I've played around with implementing this. It was a little bit trickier than I expected: since I hadn't done anything with Angular in a couple years, I'd forgotten some of the details about how scopes work. But here, have a pull request. See if you like that way of doing it, or if you'd prefer a different approach.

**Comment by ddddirk** [comment]
Marking this finished, with a small caveat:

When accessing decks through the url interface (like the link which is provided at the top of the markdown and bbcode lists), notes will not be imported, unless they are already in your localstorage. This would require adding the decknotes to the portion of the deck that gets compressed, which I'd like to leave untouched for now.
